Pop up projects info
juanmanuelbyc/Microverse-Student-Project-1 pull request #10
Opened 2022-07-20 10:23 UTC by juanmanuelbyc

xxxxxxxx

2022-07-20 14:07 UTC, 1GORDON requested changes
##
## Hi @juanmanuelbyc & @Bateyjosue ✋

Good job so far!

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Professional Readme ✔️
- Linters are passing ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

- [ ] You may please add a description to your pull request. This is where you explain or list what you accomplished within the project.
![description](https://user-images.githubusercontent.com/63917725/179999369-bf00a4a2-679e-48fa-9186-3eefc8472afe.PNG)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-20 14:07 UTC, 1GORDON commented on css/styles.css
>    }
Hello team ✋

- [ ] You may kindly fix the image on the desktop popup, as it appears stretched compared to the one provided in the Figma design.
- [ ]  You may also position the image properly as it seem to have wider margins on the left and right.
- Your design
![Your image](https://user-images.githubusercontent.com/63917725/180001272-6d61b9ce-c42a-41c9-bc35-47528c532197.PNG)

- Figma design
![Figma image](https://user-images.githubusercontent.com/63917725/180001353-70608c68-b306-4e9b-a2ee-23ae5c69c51d.PNG)

2022-07-20 14:07 UTC, 1GORDON commented on css/styles.css
> +}
Great job team 🤝

- [ ] You may kindly fix the overflow on your mobile popup. The buttons seem to overflow as the screen size reduces.
![Overflow mobile](https://user-images.githubusercontent.com/63917725/180002197-7ce069b9-d914-4811-8fe2-e250d1778e91.PNG)

2022-07-20 17:21 UTC, juanmanuelbyc commented on css/styles.css
>    }
Thanks for the feedback. its done!

2022-07-20 17:29 UTC, juanmanuelbyc commented on css/styles.css
> +}
![image](https://user-images.githubusercontent.com/7433143/180044613-0f5932a6-cc7b-4bda-85ca-7013e4735168.png)

Could you please try a more realistic screen relationship width x height to evaluate it? or try setting a commercial device when inspecting.

On my side, it looks good

2022-07-20 18:20 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/93039359/178569876-9fcda5e8-6819-4569-95ee-acb393903a05.jpg)

### Hey @juanmanuelbyc :wave:

### Highlights :1st_place_medal:
 
:heavy_check_mark: Following HTML, CSS best practices
:heavy_check_mark: Following Project Requirements
:heavy_check_mark: Descriptive PR title
:heavy_check_mark: Descriptive branch name

Good job on implementing some of the changes requested by the previous reviewer, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @HAMMAS-SALEEM in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-20 18:20 UTC, HAMMAS-SALEEM commented on css/styles.css
> +}
## Your design in different scenarios

### Scenario 1 
![mobile-design (copy)](https://user-images.githubusercontent.com/93039359/180054343-a35528eb-28aa-4cf3-a9ec-a8a8d50d3ef3.png)
### Scenario 2
![mobile-view](https://user-images.githubusercontent.com/93039359/180051141-27acbe1a-8b7c-4ec4-bb84-5f6009257303.png)
### Figma Template 
![figma](https://user-images.githubusercontent.com/93039359/180051712-e054129b-e288-43e3-b9e9-5f4a2d025fd7.png)

- [ ] You can see that your mobile modal is behaving differently on different screens. Kindly fix this issue :blush:
You can reach out to me on slack **Hammas Bin Saleem** so we can fix this issue in one call :+1:

2022-07-21 07:36 UTC, HAMMAS-SALEEM approved these changes
# Status: Approved :green_circle:

Hey  @juanmanuelbyc :wave:

Great work on implementing the requested changes. Your project is complete. There is nothing else to say about your project. :+1:
Go ahead and merge it. :muscle:

## Highlights :1st_place_medal:
:heavy_check_mark: Following Github Flow
:heavy_check_mark: Following Linters
:heavy_check_mark: Popup is working as expected

### [Optional]

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-21 15:19 UTC, merged