Create desktop version
juanmanuelbyc/Microverse-Student-Project-1 pull request #5
Opened 2022-07-06 19:53 UTC by juanmanuelbyc

Applied all html and css changes to recreate the desktop version of my portfolio project.

2022-07-06 20:46 UTC, ishimwezachee requested changes
Hi @juanmanuelbyc , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
Linters are passing 👍 
Git flow is implemented 👍 
Project is running successfully 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-06 20:46 UTC, ishimwezachee commented on index.html
> +              </div>
- [x] You should have space between your technologies, as it is in provided figma design, please make sure that you followed the design. 
![image](https://user-images.githubusercontent.com/43877689/177638851-ea373056-9eb8-4f6c-bb73-60a30146aa5d.png)

- [ ] The background color should also be similar to the one from Figma design, the one you provided is too bright.

2022-07-06 20:46 UTC, ishimwezachee commented on index.html
- [x] In figma design the background color is not white, its is somehow gray, please use the right colors with the one provided from figma

2022-07-07 09:35 UTC, juanmanuelbyc commented on index.html
> +              </div>
done! thanks for feedback

2022-07-07 09:36 UTC, juanmanuelbyc commented on index.html
You're right. Thanks!

2022-07-07 10:14 UTC, codecaiine approved these changes
Hi @juanmanuelbyc , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Descriptive Pull request :heavy_check_mark: 
- Good use of Gitflow :heavy_check_mark: 
- Commits are meaningful :heavy_check_mark: 
-  Clean code :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-07 10:14 UTC, codecaiine commented on index.html
> +    </header>
- [ ] [OPTIONAL] Great Job with your desktop version :+1: , however, I think you could work on your navigation bar and make it stick as much as possible to the Figma template, it is very important as a full-stack developer to peer attention to details. please make sure to have the same colors, font, and background :smile:

### Figma template
![Screenshot from 2022-07-07 09-59-46](https://user-images.githubusercontent.com/6615394/177747558-17363908-a602-4657-83a5-444f10c5b1c5.png)

### Your project
![Screenshot from 2022-07-07 09-52-47](https://user-images.githubusercontent.com/6615394/177747565-3c061429-26d0-4eff-8ff0-b6e84ccccf85.png)

2022-07-07 10:14 UTC, codecaiine commented on index.html
> +              </div>
- [ ] [OPTIONAL] Great work so far,  I would like to recommend you to use list `ul` and each technology has a `li` (e.g., "JavasScript", "HTML" and "CSS").

2022-07-07 15:11 UTC, merged